services:
  - type: web
    name: plant-disease-api
    env: python
    region: oregon
    buildCommand: cd backend && pip install -r requirements.txt
    startCommand: cd backend && uvicorn app.main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /health
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: CORS_ORIGINS
        value: "*"
      - key: LOG_LEVEL
        value: info
      - key: MODEL_PATH
        value: models/best_model.h5
